SET SERVEROUTPUT ON;

CREATE PROCEDURE add_department (
    name VARCHAR2, mgr NUMBER, loc NUMBER
) IS
BEGIN 
    INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
    VALUES (DEPARTMENTS_SEQ.nextval, name, mgr, loc);
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Err: adding dept: ' || name);
END;
/